<a href="https://colab.research.google.com/github/Gopi-13-svg/PYTHO/blob/main/DAY31.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.11/dist-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.13.1)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.55.8)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.2->mlxtend) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.2->mlxtend) (2025.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)

In [ ]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [ ]:
data=[
    ['milk','bread','jam','butter','sugar'],
    ['milk','bread','egg'],
    ['beer','cola','bread','fish'],
    ['milk','bread','egg','meat'],
    ['diapers','milk','bread','jam'],
    ['milk','bread','jam','cola']
]

In [ ]:
from mlxtend.preprocessing import TransactionEncoder

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
import warnings
warnings.filterwarnings('ignore')

In [4]:
titanic =  pd.read_csv("/content/Titanic.csv")
titanic.head()

  Class Gender    Age Survived
0   3rd   Male  Child       No
1   3rd   Male  Child       No
2   3rd   Male  Child       No
3   3rd   Male  Child       No
4   3rd   Male  Child       No

In [7]:
titanic['Class'].unique()

array(['3rd', '1st', '2nd', 'Crew'], dtype=object)

In [11]:
titanic['Class'].value_counts()

Class
Crew    885
3rd     706
1st     325
2nd     285
Name: count, dtype: int64

In [12]:
titanic['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [14]:
titanic['Gender'].value_counts()

Gender
Male      1731
Female     470
Name: count, dtype: int64

In [15]:
titanic['Age'].unique()

array(['Child', 'Adult'], dtype=object)

In [16]:
titanic['Age'].value_counts()

Age
Adult    2092
Child     109
Name: count, dtype: int64

In [17]:
df=pd.get_dummies(titanic,dtype='int')
df.head()

,Class_1st,Class_2nd,Class_3rd,Class_Crew,Gender_Female,Gender_Male,Age_Adult,Age_Child,Survived_No,Survived_Yes
0,0,0,1,0,0,1,0,1,1,0
1,0,0,1,0,0,1,0,1,1,0
2,0,0,1,0,0,1,0,1,1,0
3,0,0,1,0,0,1,0,1,1,0
4,0,0,1,0,0,1,0,1,1,0

APRIORI ALGORITHM

In [18]:
frequent_itemsets = apriori(df, min_support=0.1, use_colnames=True)
frequent_itemsets

     support                                           itemsets
0   0.147660                                        (Class_1st)
1   0.129487                                        (Class_2nd)
2   0.320763                                        (Class_3rd)
3   0.402090                                       (Class_Crew)
4   0.213539                                    (Gender_Female)
5   0.786461                                      (Gender_Male)
6   0.950477                                        (Age_Adult)
7   0.676965                                      (Survived_No)
8   0.323035                                     (Survived_Yes)
9   0.144934                             (Class_1st, Age_Adult)
10  0.118582                             (Class_2nd, Age_Adult)
11  0.231713                           (Gender_Male, Class_3rd)
12  0.284871                             (Class_3rd, Age_Adult)
13  0.239891                           (Survived_No, Class_3rd)
14  0.391640                          (Gender_Male, Class_Crew)
15  0.402090                            (Age_Adult, Class_Crew)
16  0.305770                          (Survived_No, Class_Crew)
17  0.193094                         (Gender_Female, Age_Adult)
18  0.156293                      (Gender_Female, Survived_Yes)
19  0.757383                           (Gender_Male, Age_Adult)
20  0.619718                         (Gender_Male, Survived_No)
21  0.166742                        (Gender_Male, Survived_Yes)
22  0.653339                           (Survived_No, Age_Adult)
23  0.297138                          (Survived_Yes, Age_Adult)
24  0.209905                (Gender_Male, Class_3rd, Age_Adult)
25  0.191731              (Gender_Male, Survived_No, Class_3rd)
26  0.216265                (Survived_No, Class_3rd, Age_Adult)
27  0.391640               (Gender_Male, Age_Adult, Class_Crew)
28  0.304407             (Gender_Male, Survived_No, Class_Crew)
29  0.305770               (Age_Adult, Survived_No, Class_Crew)
30  0.143571           (Gender_Female, Survived_Yes, Age_Adult)
31  0.603816              (Gender_Male, Survived_No, Age_Adult)
32  0.153567             (Gender_Male, Survived_Yes, Age_Adult)
33  0.175829   (Gender_Male, Survived_No, Class_3rd, Age_Adult)
34  0.304407  (Gender_Male, Age_Adult, Survived_No, Class_Crew)

In [20]:
rules = association_rules(frequent_itemsets, metric="lift",min_threshold=1,num_itemsets=len(frequent_itemsets))
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Class_1st),(Age_Adult),0.147660,0.950477,0.144934,0.981538,1.032680,1.0,0.004587,2.682493,0.037128,0.152050,0.627212,0.567012
1,(Age_Adult),(Class_1st),0.950477,0.147660,0.144934,0.152486,1.032680,1.0,0.004587,1.005694,0.639010,0.152050,0.005661,0.567012
2,(Survived_No),(Class_3rd),0.676965,0.320763,0.239891,0.354362,1.104747,1.0,0.022745,1.052040,0.293515,0.316547,0.049466,0.551119
3,(Class_3rd),(Survived_No),0.320763,0.676965,0.239891,0.747875,1.104747,1.0,0.022745,1.281251,0.139592,0.316547,0.219513,0.551119
4,(Gender_Male),(Class_Crew),0.786461,0.402090,0.391640,0.497978,1.238474,1.0,0.075412,1.191004,0.901730,0.491448,0.160372,0.735995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,"(Survived_No, Class_Crew)","(Gender_Male, Age_Adult)",0.305770,0.757383,0.304407,0.995542,1.314450,1.0,0.072822,54.427079,0.344592,0.401198,0.981627,0.698731
70,(Gender_Male),"(Class_Crew, Survived_No, Age_Adult)",0.786461,0.305770,0.304407,0.387060,1.265851,1.0,0.063931,1.132622,0.983509,0.386390,0.117093,0.691301
71,(Age_Adult),"(Gender_Male, Survived_No, Class_Crew)",0.950477,0.304407,0.304407,0.320268,1.052103,1.0,0.015075,1.023334,1.000000,0.320268,0.022802,0.660134
72,(Survived_No),"(Class_Crew, Gender_Male, Age_Adult)",0.676965,0.391640,0.304407,0.449664,1.148157,1.0,0.039280,1.105434,0.399458,0.398335,0.095378,0.613463
73,(Class_Crew),"(Gender_Male, Survived_No, Age_Adult)",0.402090,0.603816,0.304407,0.757062,1.253795,1.0,0.061619,1.630802,0.338549,0.433938,0.386805,0.630600